# Generated by Django 5.1.2 on 2024-10-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIngrediente', models.CharField(max_length=100)),
                ('cantidadMinima', models.IntegerField()),
                ('cantidadActual', models.IntegerField()),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos', to='crud.ingrediente'),
        ),
    ]
