# Generated by Django 5.1.2 on 2024-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('Cajero', 'Cajero'), ('Administrador', 'Administrador')], default='Cajero', max_length=20),
        ),
    ]
