# Generated by Django 5.1.2 on 2024-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='producto',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='productos',
            field=models.ManyToManyField(to='crud.producto'),
        ),
    ]
