# Generated by Django 5.1.2 on 2024-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_ordencompra_producto_ordencompra_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen de producto'),
        ),
    ]
