# Generated by Django 5.1.2 on 2024-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='productos', to='crud.ingrediente'),
        ),
    ]
