# Generated by Django 5.1.2 on 2024-10-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_ingrediente_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidadActual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidadMinima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.proveedor'),
        ),
    ]
