# Generated by Django 5.1.2 on 2024-10-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_alter_producto_cantidadactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidadActual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_ordenados', to='crud.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.producto')),
            ],
        ),
    ]
